import { Poppins } from "next/font/google"
import "./globals.css";
import { ThemeProvider } from "@/components/Provider/ThemProvider";



const font = Poppins({
  subsets : ["latin"],
  weight : ["400" , "600"]
})
export const metadata = {
  title: "EduText",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`${font.className} dark:bg-stone-900`}
      >
        <ThemeProvider 
          attribute = "class"
          defaultTheme = "system"
          enableSystem
          disableTransitionOnChange
          storageKey = "jotion-theme-2"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
